## Insider Trading Database Compiling

Imports

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import yfinance as yf
import seaborn as sns
from datetime import datetime, timedelta
import time

In [2]:
#timing notebook compiling time
start_time = time.time()

## Scraping OpenInsider
50 pages is beginning of September
Currently at 10 per page in url! can switch to 5000
0.283 seconds per row.
5000 rows is 9.05min and beginning of november. 10000 is 12min and mid sept.

In [3]:
rowcount = 5000
numpages = 30
baseurl = ('http://openinsider.com/screener?s=&o=&pl=&ph=&ll=&lh=&fd=0&fdr=&td=-1&tdr=11%2F30%2F2022+-+11%2F29%2F2023&fdlyl=&fdlyh=&daysago=&xp=1&xs=1&vl=&vh=&ocl=&och=&sic1=-1&sicl=100&sich=9999&isofficer=1&iscob=1&isceo=1&ispres=1&iscoo=1&iscfo=1&isgc=1&isvp=1&isdirector=1&istenpercent=1&isother=1&grp=0&nfl=&nfh=&nil=&nih=&nol=&noh=&v2l=&v2h=&oc2l=&oc2h=&sortcol=1&cnt=' + str(rowcount)+ '&page=')
InsTrade = pd.DataFrame()

In [4]:
for pagenumber in range(1, numpages +1):
    url = baseurl + str(pagenumber)
    fullpage = pd.read_html(url)
    if len(fullpage) >= 12:
        TradeTable = fullpage[11]
        InsTrade = pd.concat([InsTrade, TradeTable], ignore_index=True)
    else:
        print('not right, try again')

In [5]:
InsTrade.tail()

,X,Filing Date,Trade Date,Ticker,Company Name,Insider Name,Title,Trade Type,Price,Qty,Owned,ΔOwn,Value,1d,1w,1m,6m
149995,M,2022-12-23 09:31:55,2022-12-21,FXNC,First National Corp /va/,Holt George Edwin III,Dir,S - Sale,$17.55,-1030,28535,-3%,"-$18,072",NaN,NaN,NaN,NaN
149996,DM,2022-12-23 09:11:42,2022-12-21,VMD,"Viemed Healthcare, Inc.",Smokoff Timothy,Dir,S - Sale+OE,$10.23,-25900,67332,-28%,"-$265,020",NaN,NaN,NaN,NaN
149997,NaN,2022-12-23 08:38:16,2022-12-21,EGLE,Eagle Bulk Shipping Inc.,Vogel Gary,CEO,S - Sale,$50.79,-15000,147521,-9%,"-$761,800",NaN,NaN,NaN,NaN
149998,NaN,2022-12-23 07:30:00,2022-12-21,AMWL,American Well Corp,Schoenberg Ido,"COB, co-CEO, 10%",S - Sale,$3.24,-132006,1946471,-6%,"-$427,647",NaN,NaN,NaN,NaN
149999,NaN,2022-12-23 07:27:43,2022-12-21,AMWL,American Well Corp,Schoenberg Roy,"Pres, co-CEO, 10%",S - Sale,$3.23,-125696,2290936,-5%,"-$406,275",NaN,NaN,NaN,NaN

In [6]:
RemoveColumns = ['X','1d','1w','1m','6m']
for column in RemoveColumns:
    if column in InsTrade.columns:
        InsTrade.drop(columns=column, inplace=True)
InsTrade.head()

,Filing Date,Trade Date,Ticker,Company Name,Insider Name,Title,Trade Type,Price,Qty,Owned,ΔOwn,Value
0,2023-12-05 21:21:25,2023-11-30,LQDA,Liquidia Corp,Lippe Robert A,Chief Operations Officer,S - Sale+OE,$7.28,-497,193788,0%,"-$3,618"
1,2023-12-05 21:18:24,2023-11-30,LQDA,Liquidia Corp,Moomaw Scott,Chief Commercial Officer,S - Sale+OE,$7.28,-542,106737,-1%,"-$3,946"
2,2023-12-05 21:15:33,2023-11-30,LQDA,Liquidia Corp,Adair Jason,Chief Business Officer,S - Sale+OE,$7.28,-452,54478,-1%,"-$3,291"
3,2023-12-05 21:08:03,2023-11-30,IMGN,"Immunogen, Inc.",Coen Stacy Ann,"SVP, Chief Business Officer",S - Sale,$29.20,-3826,33140,-10%,"-$111,719"
4,2023-12-05 21:06:37,2023-11-30,IMGN,"Immunogen, Inc.",Peterson Kristine,Dir,S - Sale+OE,$28.90,-20000,0,-100%,"-$578,000"

In [7]:
#rename columns
InsTradeHeaders = ["FDate", "TDate", "Ticker", "Company", "Insider", "Title", "TradeType", "Price", "Qty", "Owned", "OwnChange", "Value"]
InsTrade.columns = InsTradeHeaders
InsTrade.head(-5)

,FDate,TDate,Ticker,Company,Insider,Title,TradeType,Price,Qty,Owned,OwnChange,Value
0,2023-12-05 21:21:25,2023-11-30,LQDA,Liquidia Corp,Lippe Robert A,Chief Operations Officer,S - Sale+OE,$7.28,-497,193788,0%,"-$3,618"
1,2023-12-05 21:18:24,2023-11-30,LQDA,Liquidia Corp,Moomaw Scott,Chief Commercial Officer,S - Sale+OE,$7.28,-542,106737,-1%,"-$3,946"
2,2023-12-05 21:15:33,2023-11-30,LQDA,Liquidia Corp,Adair Jason,Chief Business Officer,S - Sale+OE,$7.28,-452,54478,-1%,"-$3,291"
3,2023-12-05 21:08:03,2023-11-30,IMGN,"Immunogen, Inc.",Coen Stacy Ann,"SVP, Chief Business Officer",S - Sale,$29.20,-3826,33140,-10%,"-$111,719"
4,2023-12-05 21:06:37,2023-11-30,IMGN,"Immunogen, Inc.",Peterson Kristine,Dir,S - Sale+OE,$28.90,-20000,0,-100%,"-$578,000"
...,...,...,...,...,...,...,...,...,...,...,...,...
149990,2022-12-23 12:20:02,2022-12-21,UDMY,"Udemy, Inc.",Venugopal Venu,CTO,S - Sale,$3.52,-7524,263006,-3%,"-$26,462"
149991,2022-12-23 10:18:11,2022-12-21,HUM,Humana Inc,Jones David A Jr/ky,Dir,S - Sale+OE,$501.72,-15000,43240,-26%,"-$7,525,800"
149992,2022-12-23 10:13:20,2022-12-21,MORN,"Morningstar, Inc.",Mansueto Joseph D,"Exec COB, 10%",S - Sale,$214.36,-20863,16640542,0%,"-$4,472,134"
149993,2022-12-23 09:52:22,2022-12-21,HTBI,"Hometrust Bancshares, Inc.",Vuncannon Tony J.,"EVP, CFO, Treasurer",S - Sale+OE,$24.57,-9155,73832,-11%,"-$224,980"
149994,2022-12-23 09:42:42,2022-12-21,DKS,"Dick'S Sporting Goods, Inc.",Rak Vladimir,"EVP, CTO",S - Sale+OE,$112.43,-29144,48260,-38%,"-$3,276,688"

In [8]:
TitleCount = InsTrade.Title.value_counts()
TitleCount.head(20)

Dir                         30358
10%                         14167
CFO                          8427
CEO                          7900
Pres, CEO                    5848
Dir, 10%                     3843
COO                          2878
See Remarks                  2447
GC                           2405
CTO                          1901
Co-CEO, Co-Founder, 10%      1773
EVP, CFO                     1773
Chief Medical Officer        1641
CEO, 10%                     1624
EVP                          1574
Chief Commercial Officer     1330
Pres                         1203
Chief Accounting Officer     1137
Chief Scientific Officer     1101
CEO, Pres                    1078
Name: Title, dtype: int64

In [9]:
TickerCount = InsTrade.Ticker.value_counts()
TickerCount.head(20)

TEAM    1838
DNA     1347
BLZE    1314
CRM     1095
TPL      838
XM       721
UTHR     559
PTCT     545
ED       535
NBIX     529
NTRA     509
AEHR     482
FLYW     472
CMPO     471
IOT      467
NGM      466
AKAM     466
LLAP     447
JBL      442
TOST     438
Name: Ticker, dtype: int64

In [10]:
InsTrade.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 12 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   FDate      150000 non-null  object
 1   TDate      150000 non-null  object
 2   Ticker     149928 non-null  object
 3   Company    150000 non-null  object
 4   Insider    150000 non-null  object
 5   Title      150000 non-null  object
 6   TradeType  150000 non-null  object
 7   Price      150000 non-null  object
 8   Qty        150000 non-null  int64
 9   Owned      150000 non-null  int64
 10  OwnChange  150000 non-null  object
 11  Value      150000 non-null  object
dtypes: int64(2), object(10)
memory usage: 13.7+ MB

#removing problem tickers from below profitability calc
error_tickers = pd.read_csv('error_tickers.csv')['ErrorTickers'].tolist()

InsTrade = InsTrade[~InsTrade['Ticker'].isin(error_tickers)]
InsTrade.reset_index(drop=True, inplace=True)

In [11]:
InsTrade.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 12 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   FDate      150000 non-null  object
 1   TDate      150000 non-null  object
 2   Ticker     149928 non-null  object
 3   Company    150000 non-null  object
 4   Insider    150000 non-null  object
 5   Title      150000 non-null  object
 6   TradeType  150000 non-null  object
 7   Price      150000 non-null  object
 8   Qty        150000 non-null  int64
 9   Owned      150000 non-null  int64
 10  OwnChange  150000 non-null  object
 11  Value      150000 non-null  object
dtypes: int64(2), object(10)
memory usage: 13.7+ MB

## Changing Dataframe Data Types
Filing data/trade date to datetime
Price, Qty, Owned, own change, and value to float/int

In [12]:
instrade = InsTrade

In [13]:
columns_to_replace = ['Price', 'Value', 'OwnChange', 'Qty']
for column in columns_to_replace:
    instrade[column] = instrade[column].apply(lambda x: str(x).replace('$', '').replace(',', '').replace('%', '').replace('+', '').replace('New', '').replace('>999', '999'))
instrade.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 12 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   FDate      150000 non-null  object
 1   TDate      150000 non-null  object
 2   Ticker     149928 non-null  object
 3   Company    150000 non-null  object
 4   Insider    150000 non-null  object
 5   Title      150000 non-null  object
 6   TradeType  150000 non-null  object
 7   Price      150000 non-null  object
 8   Qty        150000 non-null  object
 9   Owned      150000 non-null  int64
 10  OwnChange  150000 non-null  object
 11  Value      150000 non-null  object
dtypes: int64(1), object(11)
memory usage: 13.7+ MB

In [14]:
instrade[["Price","Qty","Owned","OwnChange","Value"]] = instrade[["Price","Qty","Owned","OwnChange","Value"]].apply(pd.to_numeric)

In [15]:
#Changing OwnChange to percentage
instrade['OwnChange'] = instrade['OwnChange']/100

In [16]:
#DateTime Change FDate and TDate
instrade[["FDate","TDate"]] = instrade[["FDate","TDate"]].apply(pd.to_datetime)

## Consumer Sentiment Import and Clean

In [17]:
aaii = pd.read_excel(r"C:\Users\lkasc\Documents\Weber State University\2023 FALL\MIS 2040 BUSI ANALYTICS WITH PYTHON\Final Project\Consumer Sentiment\Cleaned, Daily Investor Sentiment AAII.xlsx")
aaii.head()

,Date,Bullish,Neutral,Bearish,Bullish 8-Week Moving Average,Bull-Bear Spread,S&P 500 Weekly High,S&P 500 Weekly Low,S&P 500 Weekly Close
0,2023-11-30,0.487578,0.31677,0.195652,0.487578,0.291926,4587.64,4540.51,4550.58
1,2023-11-29,0.487578,0.31677,0.195652,0.487578,0.291926,4587.64,4540.51,4550.58
2,2023-11-28,0.487578,0.31677,0.195652,0.487578,0.291926,4587.64,4540.51,4550.58
3,2023-11-27,0.487578,0.31677,0.195652,0.487578,0.291926,4587.64,4540.51,4550.58
4,2023-11-26,0.487578,0.31677,0.195652,0.487578,0.291926,4587.64,4540.51,4550.58

In [18]:
RemoveaaiiColumns = ['S&P 500 Weekly High', 'S&P 500 Weekly Low', 'S&P 500 Weekly Close']
for column in RemoveaaiiColumns:
    if column in aaii.columns:
        aaii.drop(columns=column, inplace=True)
aaii.head()

,Date,Bullish,Neutral,Bearish,Bullish 8-Week Moving Average,Bull-Bear Spread
0,2023-11-30,0.487578,0.31677,0.195652,0.487578,0.291926
1,2023-11-29,0.487578,0.31677,0.195652,0.487578,0.291926
2,2023-11-28,0.487578,0.31677,0.195652,0.487578,0.291926
3,2023-11-27,0.487578,0.31677,0.195652,0.487578,0.291926
4,2023-11-26,0.487578,0.31677,0.195652,0.487578,0.291926

In [19]:
#data types are correct
aaii.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2160 entries, 0 to 2159
Data columns (total 6 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Date                           2160 non-null   datetime64[ns]
 1   Bullish                        2160 non-null   float64
 2   Neutral                        2160 non-null   float64
 3   Bearish                        2160 non-null   float64
 4   Bullish 8-Week Moving Average  2160 non-null   float64
 5   Bull-Bear Spread               2160 non-null   float64
dtypes: datetime64[ns](1), float64(5)
memory usage: 101.4 KB

In [20]:
aaii.sort_values(by=['Date'], ascending=False)
aaii.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2160 entries, 0 to 2159
Data columns (total 6 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Date                           2160 non-null   datetime64[ns]
 1   Bullish                        2160 non-null   float64
 2   Neutral                        2160 non-null   float64
 3   Bearish                        2160 non-null   float64
 4   Bullish 8-Week Moving Average  2160 non-null   float64
 5   Bull-Bear Spread               2160 non-null   float64
dtypes: datetime64[ns](1), float64(5)
memory usage: 101.4 KB

In [21]:
instrade.sort_values(by=['TDate'], ascending=False)

,FDate,TDate,Ticker,Company,Insider,Title,TradeType,Price,Qty,Owned,OwnChange,Value
0,2023-12-05 21:21:25,2023-11-30,LQDA,Liquidia Corp,Lippe Robert A,Chief Operations Officer,S - Sale+OE,7.28,-497,193788,0.00,-3618
161,2023-11-30 16:06:01,2023-11-30,GGG,Graco Inc,Wordell Angela F,"EVP, Operations",S - Sale+OE,80.27,-2895,14939,-0.16,-232381
149,2023-11-30 18:16:52,2023-11-30,VMC,Vulcan Materials Co,Clement David P,SVP,S - Sale+OE,212.00,-764,3144,-0.20,-161968
150,2023-11-30 18:01:01,2023-11-30,HPQ,Hp Inc,Cho Alex,"Pres, Personal Systems",S - Sale+OE,29.24,-45758,22003,-0.68,-1337964
151,2023-11-30 17:40:57,2023-11-30,HLI,"Houlihan Lokey, Inc.",Alley J Lindsey,CFO,S - Sale+OE,107.48,-10000,0,-1.00,-1074800
...,...,...,...,...,...,...,...,...,...,...,...,...
59975,2022-12-23 16:15:27,2022-12-21,BWMN,Bowman Consulting Group Ltd.,Labovitz Bruce J,CFO,S - Sale,20.00,-3000,293629,-0.01,-60000
59974,2022-12-23 16:19:33,2022-12-21,ASAN,"Asana, Inc.",Lacey Eleanor B,"GC, Corporate Secretary",S - Sale,13.65,-2034,166270,-0.01,-27764
59973,2022-12-23 16:18:54,2022-12-21,DNA,"Ginkgo Bioworks Holdings, Inc.",Canton Barry,10%,S - Sale,1.68,-805193,35982041,-0.02,-1353334
59972,2022-12-23 16:21:20,2022-12-21,DNA,"Ginkgo Bioworks Holdings, Inc.",Kelly Jason R,See remarks,S - Sale,1.68,-402596,17991004,-0.02,-676666
149999,2022-12-23 07:27:43,2022-12-21,AMWL,American Well Corp,Schoenberg Roy,"Pres, co-CEO, 10%",S - Sale,3.23,-125696,2290936,-0.05,-406275

Merge

In [22]:
iaaiidict = aaii.set_index('Date').to_dict()

# Map values from aaii to instrade based on the TDate column
iaaii = instrade.copy()
for col in aaii.columns[1:]:
    iaaii[col] = iaaii['TDate'].map(iaaiidict[col])

In [23]:
iaaii.fillna(np.nan, inplace=True)

In [24]:
iaaii.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 17 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   FDate                          150000 non-null  datetime64[ns]
 1   TDate                          150000 non-null  datetime64[ns]
 2   Ticker                         149928 non-null  object
 3   Company                        150000 non-null  object
 4   Insider                        150000 non-null  object
 5   Title                          150000 non-null  object
 6   TradeType                      150000 non-null  object
 7   Price                          150000 non-null  float64
 8   Qty                            150000 non-null  int64
 9   Owned                          150000 non-null  int64
 10  OwnChange                      148594 non-null  float64
 11  Value                          150000 non-null  int64
 12  Bullish                        150000 non-null  float64
 13  Neutral                        150000 non-null  float64
 14  Bearish                        150000 non-null  float64
 15  Bullish 8-Week Moving Average  150000 non-null  float64
 16  Bull-Bear Spread               150000 non-null  float64
dtypes: datetime64[ns](2), float64(7), int64(3), object(5)
memory usage: 19.5+ MB

In [25]:
print(aaii[['Bullish', 'Neutral', 'Bearish']].isnull().sum())
print(instrade['TDate'].isnull().sum())

Bullish    0
Neutral    0
Bearish    0
dtype: int64
0

In [26]:
print(instrade['TDate'].unique())

['2023-11-30T00:00:00.000000000' '2023-11-29T00:00:00.000000000'
 '2023-11-28T00:00:00.000000000' '2023-11-27T00:00:00.000000000'
 '2023-11-24T00:00:00.000000000' '2023-11-23T00:00:00.000000000'
 '2023-11-22T00:00:00.000000000' '2023-11-21T00:00:00.000000000'
 '2023-11-20T00:00:00.000000000' '2023-11-19T00:00:00.000000000'
 '2023-11-18T00:00:00.000000000' '2023-11-17T00:00:00.000000000'
 '2023-11-16T00:00:00.000000000' '2023-11-15T00:00:00.000000000'
 '2023-11-14T00:00:00.000000000' '2023-11-13T00:00:00.000000000'
 '2023-11-10T00:00:00.000000000' '2023-11-09T00:00:00.000000000'
 '2023-11-08T00:00:00.000000000' '2023-11-07T00:00:00.000000000'
 '2023-11-06T00:00:00.000000000' '2023-11-03T00:00:00.000000000'
 '2023-11-02T00:00:00.000000000' '2023-11-01T00:00:00.000000000'
 '2023-10-31T00:00:00.000000000' '2023-10-30T00:00:00.000000000'
 '2023-10-27T00:00:00.000000000' '2023-10-26T00:00:00.000000000'
 '2023-10-25T00:00:00.000000000' '2023-10-24T00:00:00.000000000'
 '2023-10-23T00:00:00.000000000' '2023-10-20T00:00:00.000000000'
 '2023-10-19T00:00:00.000000000' '2023-10-18T00:00:00.000000000'
 '2023-10-17T00:00:00.000000000' '2023-10-16T00:00:00.000000000'
 '2023-10-15T00:00:00.000000000' '2023-10-13T00:00:00.000000000'
 '2023-10-12T00:00:00.000000000' '2023-10-11T00:00:00.000000000'
 '2023-10-10T00:00:00.000000000' '2023-10-09T00:00:00.000000000'
 '2023-10-06T00:00:00.000000000' '2023-10-05T00:00:00.000000000'
 '2023-10-04T00:00:00.000000000' '2023-10-03T00:00:00.000000000'
 '2023-10-02T00:00:00.000000000' '2023-10-01T00:00:00.000000000'
 '2023-09-29T00:00:00.000000000' '2023-09-28T00:00:00.000000000'
 '2023-09-27T00:00:00.000000000' '2023-09-26T00:00:00.000000000'
 '2023-09-25T00:00:00.000000000' '2023-09-22T00:00:00.000000000'
 '2023-09-21T00:00:00.000000000' '2023-09-20T00:00:00.000000000'
 '2023-09-19T00:00:00.000000000' '2023-09-18T00:00:00.000000000'
 '2023-09-15T00:00:00.000000000' '2023-09-14T00:00:00.000000000'
 '2023-09-13T00:00:00.000000000' '2023-09-12T00:00:00.000000000'
 '2023-09-11T00:00:00.000000000' '2023-09-10T00:00:00.000000000'
 '2023-09-08T00:00:00.000000000' '2023-09-07T00:00:00.000000000'
 '2023-09-06T00:00:00.000000000' '2023-09-05T00:00:00.000000000'
 '2023-09-04T00:00:00.000000000' '2023-09-01T00:00:00.000000000'
 '2023-08-31T00:00:00.000000000' '2023-08-30T00:00:00.000000000'
 '2023-08-29T00:00:00.000000000' '2023-08-28T00:00:00.000000000'
 '2023-08-25T00:00:00.000000000' '2023-08-24T00:00:00.000000000'
 '2023-08-23T00:00:00.000000000' '2023-08-22T00:00:00.000000000'
 '2023-08-21T00:00:00.000000000' '2023-08-20T00:00:00.000000000'
 '2023-08-19T00:00:00.000000000' '2023-08-18T00:00:00.000000000'
 '2023-08-17T00:00:00.000000000' '2023-08-16T00:00:00.000000000'
 '2023-08-15T00:00:00.000000000' '2023-08-14T00:00:00.000000000'
 '2023-08-12T00:00:00.000000000' '2023-08-11T00:00:00.000000000'
 '2023-08-10T00:00:00.000000000' '2023-08-09T00:00:00.000000000'
 '2023-08-08T00:00:00.000000000' '2023-08-07T00:00:00.000000000'
 '2023-08-04T00:00:00.000000000' '2023-08-03T00:00:00.000000000'
 '2023-08-02T00:00:00.000000000' '2023-08-01T00:00:00.000000000'
 '2023-07-31T00:00:00.000000000' '2023-07-30T00:00:00.000000000'
 '2023-07-28T00:00:00.000000000' '2023-07-27T00:00:00.000000000'
 '2023-07-26T00:00:00.000000000' '2023-07-25T00:00:00.000000000'
 '2023-07-24T00:00:00.000000000' '2023-07-23T00:00:00.000000000'
 '2023-07-21T00:00:00.000000000' '2023-07-20T00:00:00.000000000'
 '2023-07-19T00:00:00.000000000' '2023-07-18T00:00:00.000000000'
 '2023-07-17T00:00:00.000000000' '2023-07-15T00:00:00.000000000'
 '2023-07-14T00:00:00.000000000' '2023-07-13T00:00:00.000000000'
 '2023-07-12T00:00:00.000000000' '2023-07-11T00:00:00.000000000'
 '2023-07-10T00:00:00.000000000' '2023-07-07T00:00:00.000000000'
 '2023-07-06T00:00:00.000000000' '2023-07-05T00:00:00.000000000'
 '2023-07-03T00:00:00.000000000' '2023-07-02T00:00:00.000000000'
 '2023-07-01T00:00:00.000000000' '2023-06-30T00:00:00.000000000'
 '2023-06-29T00:00:00.000000000' '2023-06-28T00:00:00.000000000'
 '2023-06-27T00:00:00.000000000' '2023-06-26T00:00:00.000000000'
 '2023-06-23T00:00:00.000000000' '2023-06-22T00:00:00.000000000'
 '2023-06-21T00:00:00.000000000' '2023-06-20T00:00:00.000000000'
 '2023-06-19T00:00:00.000000000' '2023-06-16T00:00:00.000000000'
 '2023-06-15T00:00:00.000000000' '2023-06-14T00:00:00.000000000'
 '2023-06-13T00:00:00.000000000' '2023-06-12T00:00:00.000000000'
 '2023-06-09T00:00:00.000000000' '2023-06-08T00:00:00.000000000'
 '2023-06-07T00:00:00.000000000' '2023-06-06T00:00:00.000000000'
 '2023-06-05T00:00:00.000000000' '2023-06-04T00:00:00.000000000'
 '2023-06-03T00:00:00.000000000' '2023-06-02T00:00:00.000000000'
 '2023-06-01T00:00:00.000000000' '2023-05-31T00:00:00.000000000'
 '2023-05-30T00:00:00.000000000' '2023-05-29T00:00:00.000000000'
 '2023-05-28T00:00:00.000000000' '2023-05-26T00:00:00.000000000'
 '2023-05-25T00:00:00.000000000' '2023-05-24T00:00:00.000000000'
 '2023-05-23T00:00:00.000000000' '2023-05-22T00:00:00.000000000'
 '2023-05-19T00:00:00.000000000' '2023-05-18T00:00:00.000000000'
 '2023-05-17T00:00:00.000000000' '2023-05-16T00:00:00.000000000'
 '2023-05-15T00:00:00.000000000' '2023-05-12T00:00:00.000000000'
 '2023-05-11T00:00:00.000000000' '2023-05-10T00:00:00.000000000'
 '2023-05-09T00:00:00.000000000' '2023-05-08T00:00:00.000000000'
 '2023-05-06T00:00:00.000000000' '2023-05-05T00:00:00.000000000'
 '2023-05-04T00:00:00.000000000' '2023-05-03T00:00:00.000000000'
 '2023-05-02T00:00:00.000000000' '2023-05-01T00:00:00.000000000'
 '2023-04-28T00:00:00.000000000' '2023-04-27T00:00:00.000000000'
 '2023-04-26T00:00:00.000000000' '2023-04-25T00:00:00.000000000'
 '2023-04-24T00:00:00.000000000' '2023-04-23T00:00:00.000000000'
 '2023-04-21T00:00:00.000000000' '2023-04-20T00:00:00.000000000'
 '2023-04-19T00:00:00.000000000' '2023-04-18T00:00:00.000000000'
 '2023-04-17T00:00:00.000000000' '2023-04-14T00:00:00.000000000'
 '2023-04-13T00:00:00.000000000' '2023-04-12T00:00:00.000000000'
 '2023-04-11T00:00:00.000000000' '2023-04-10T00:00:00.000000000'
 '2023-04-07T00:00:00.000000000' '2023-04-06T00:00:00.000000000'
 '2023-04-05T00:00:00.000000000' '2023-04-04T00:00:00.000000000'
 '2023-04-03T00:00:00.000000000' '2023-04-01T00:00:00.000000000'
 '2023-03-31T00:00:00.000000000' '2023-03-30T00:00:00.000000000'
 '2023-03-29T00:00:00.000000000' '2023-03-28T00:00:00.000000000'
 '2023-03-27T00:00:00.000000000' '2023-03-24T00:00:00.000000000'
 '2023-03-23T00:00:00.000000000' '2023-03-22T00:00:00.000000000'
 '2023-03-21T00:00:00.000000000' '2023-03-20T00:00:00.000000000'
 '2023-03-18T00:00:00.000000000' '2023-03-17T00:00:00.000000000'
 '2023-03-16T00:00:00.000000000' '2023-03-15T00:00:00.000000000'
 '2023-03-14T00:00:00.000000000' '2023-03-13T00:00:00.000000000'
 '2023-03-10T00:00:00.000000000' '2023-03-09T00:00:00.000000000'
 '2023-03-08T00:00:00.000000000' '2023-03-07T00:00:00.000000000'
 '2023-03-06T00:00:00.000000000' '2023-03-05T00:00:00.000000000'
 '2023-03-03T00:00:00.000000000' '2023-03-02T00:00:00.000000000'
 '2023-03-01T00:00:00.000000000' '2023-02-28T00:00:00.000000000'
 '2023-02-27T00:00:00.000000000' '2023-02-26T00:00:00.000000000'
 '2023-02-24T00:00:00.000000000' '2023-02-23T00:00:00.000000000'
 '2023-02-22T00:00:00.000000000' '2023-02-21T00:00:00.000000000'
 '2023-02-20T00:00:00.000000000' '2023-02-19T00:00:00.000000000'
 '2023-02-17T00:00:00.000000000' '2023-02-16T00:00:00.000000000'
 '2023-02-15T00:00:00.000000000' '2023-02-14T00:00:00.000000000'
 '2023-02-13T00:00:00.000000000' '2023-02-11T00:00:00.000000000'
 '2023-02-10T00:00:00.000000000' '2023-02-09T00:00:00.000000000'
 '2023-02-08T00:00:00.000000000' '2023-02-07T00:00:00.000000000'
 '2023-02-06T00:00:00.000000000' '2023-02-04T00:00:00.000000000'
 '2023-02-03T00:00:00.000000000' '2023-02-02T00:00:00.000000000'
 '2023-02-01T00:00:00.000000000' '2023-01-31T00:00:00.000000000'
 '2023-01-30T00:00:00.000000000' '2023-01-27T00:00:00.000000000'
 '2023-01-26T00:00:00.000000000' '2023-01-25T00:00:00.000000000'
 '2023-01-24T00:00:00.000000000' '2023-01-23T00:00:00.000000000'
 '2023-01-21T00:00:00.000000000' '2023-01-20T00:00:00.000000000'
 '2023-01-19T00:00:00.000000000' '2023-01-18T00:00:00.000000000'
 '2023-01-17T00:00:00.000000000' '2023-01-16T00:00:00.000000000'
 '2023-01-15T00:00:00.000000000' '2023-01-14T00:00:00.000000000'
 '2023-01-13T00:00:00.000000000' '2023-01-12T00:00:00.000000000'
 '2023-01-11T00:00:00.000000000' '2023-01-10T00:00:00.000000000'
 '2023-01-09T00:00:00.000000000' '2023-01-06T00:00:00.000000000'
 '2023-01-05T00:00:00.000000000' '2023-01-04T00:00:00.000000000'
 '2023-01-03T00:00:00.000000000' '2023-01-01T00:00:00.000000000'
 '2022-12-31T00:00:00.000000000' '2022-12-30T00:00:00.000000000'
 '2022-12-29T00:00:00.000000000' '2022-12-28T00:00:00.000000000'
 '2022-12-27T00:00:00.000000000' '2022-12-23T00:00:00.000000000'
 '2022-12-22T00:00:00.000000000' '2022-12-21T00:00:00.000000000']

In [27]:
print(aaii['Date'].unique())

['2023-11-30T00:00:00.000000000' '2023-11-29T00:00:00.000000000'
 '2023-11-28T00:00:00.000000000' ... '2018-01-03T00:00:00.000000000'
 '2018-01-02T00:00:00.000000000' '2018-01-01T00:00:00.000000000']

## Adding Yahoo Finance Elements with Yfinance 
(thank you chatGPT)
pip install yfinance --upgrade --no-cache-dir

In [28]:
unique_tickers = iaaii['Ticker'].unique()

tssinfo = pd.DataFrame()

for ticker in unique_tickers:
    try:
        info = yf.Ticker(ticker).info
        stock_info = pd.DataFrame({
            'Ticker': [ticker],
            'State': [info.get('state')],
            'Sector': [info.get('sector')],
            'Industry': [info.get('industry')],
            'Market Cap': [info.get('marketCap')]
        })
        tssinfo = pd.concat([tssinfo, stock_info], ignore_index=True)
    except:
        pass

In [29]:
iaaii = pd.merge(iaaii, tssinfo, on='Ticker', how='left')

In [30]:
sp500 = '^GSPC'
sp500_data = yf.download(sp500, start='2023-01-01', end='2023-12-31')
sp500_close_dict = dict(zip(sp500_data.index, sp500_data['Close']))
iaaii['S&P 500 Close'] = iaaii['TDate'].map(sp500_close_dict)

[*********************100%%**********************]  1 of 1 completed

In [31]:
iaaii.head()

,FDate,TDate,Ticker,Company,Insider,Title,TradeType,Price,Qty,Owned,...,Bullish,Neutral,Bearish,Bullish 8-Week Moving Average,Bull-Bear Spread,State,Sector,Industry,Market Cap,S&P 500 Close
0,2023-12-05 21:21:25,2023-11-30,LQDA,Liquidia Corp,Lippe Robert A,Chief Operations Officer,S - Sale+OE,7.28,-497,193788,...,0.487578,0.31677,0.195652,0.487578,0.291926,NC,Healthcare,Biotechnology,464723360,4567.799805
1,2023-12-05 21:18:24,2023-11-30,LQDA,Liquidia Corp,Moomaw Scott,Chief Commercial Officer,S - Sale+OE,7.28,-542,106737,...,0.487578,0.31677,0.195652,0.487578,0.291926,NC,Healthcare,Biotechnology,464723360,4567.799805
2,2023-12-05 21:15:33,2023-11-30,LQDA,Liquidia Corp,Adair Jason,Chief Business Officer,S - Sale+OE,7.28,-452,54478,...,0.487578,0.31677,0.195652,0.487578,0.291926,NC,Healthcare,Biotechnology,464723360,4567.799805
3,2023-12-05 21:08:03,2023-11-30,IMGN,"Immunogen, Inc.",Coen Stacy Ann,"SVP, Chief Business Officer",S - Sale,29.20,-3826,33140,...,0.487578,0.31677,0.195652,0.487578,0.291926,MA,Healthcare,Biotechnology,7936178176,4567.799805
4,2023-12-05 21:06:37,2023-11-30,IMGN,"Immunogen, Inc.",Peterson Kristine,Dir,S - Sale+OE,28.90,-20000,0,...,0.487578,0.31677,0.195652,0.487578,0.291926,MA,Healthcare,Biotechnology,7936178176,4567.799805

## Calculating Profitability
Assumes 180 days since TDate or current date. Should create separate database with only purchases and calc/graph profitability based on that.
Should be modified to ensure that only purchase dates are used.
180 days value should also be changed to reflect average holding period.

In [32]:
TradeTypecounts = iaaii.TradeType.value_counts()
TradeTypecounts

S - Sale        79594
S - Sale+OE     36970
P - Purchase    33436
Name: TradeType, dtype: int64

In [33]:
def calculate_profitability(row):
    stock_symbol = row['Ticker']
    trade_date = row['TDate']
    trade_type = row['TradeType']
    shares = row['Qty']

    try:
        if trade_type.startswith('P'):
            stock_data = yf.download(stock_symbol, start=trade_date, end=trade_date + timedelta(days=180), progress=False)
        elif trade_type.startswith('S'):
            stock_data = yf.download(stock_symbol, start=trade_date - timedelta(days=180), end=trade_date, progress=False)
        else:
            return pd.Series({'Percentage Profit': 0.0, 'Dollar Profit': 0.0})

        if stock_data.empty:
            return pd.Series({'Percentage Profit': 0.0, 'Dollar Profit': 0.0})

        closing_prices = stock_data['Close']

        if trade_type.startswith('P'):
            end_date = min(trade_date + timedelta(days=180), pd.to_datetime('2023-11-30'))
        else:
            end_date = max(trade_date - timedelta(days=180), pd.to_datetime('2023-01-01'))

        closing_prices = closing_prices[(closing_prices.index >= end_date) | (closing_prices.index <= end_date)]

        purchase_price = closing_prices.iloc[0]
        current_price = closing_prices.iloc[-1]
        percentage_profit = ((current_price - purchase_price) / purchase_price)
        dollar_profit = (current_price - purchase_price) * shares

    except Exception as e:
        #error_tickers.append(stock_symbol)
        print(f"problem downloading {stock_symbol}: {str(e)}")
        return pd.Series({'Percentage Profit': 0.0, 'Dollar Profit': 0.0})

    return pd.Series({'Percentage Profit': percentage_profit, 'Dollar Profit': dollar_profit})

In [ ]:
#profit_df = iaaii.apply(calculate_profitability, axis=1)
#iaaii = pd.concat([iaaii, profit_df], axis=1)
iaaii[['Percentage Profit', 'Dollar Profit']] = iaaii.apply(calculate_profitability, axis=1)

1 Failed download:
['BIOBI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GTII.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GTII.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ZANDZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ZANDZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CRDAC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OAK.P']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ZANDZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['WI']: Exception('%ticker%: No price data found, symbol may be delisted (1d 2023-05-21 00:00:00 -> 2023-11-17 00:00:00)')

1 Failed download:
['ZANDZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LBTY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['UHALU']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['UHALU']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ZANDZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ZANDZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ZANDZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ZANDZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ZANDZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ZANDZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ZANDZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LSFP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SZL.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ZANDZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SZL.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PLNHF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['NYSE.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LBTY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SNVPR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SNVPR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SNVPR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SNVPR']: Exception('%ticker%: No timezone found, symbol may be delisted')

problem downloading nan: 'float' object has no attribute 'replace'
problem downloading nan: 'float' object has no attribute 'replace'

1 Failed download:
['NYSE.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SNVPR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['DTOC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ADER']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SNVPR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LBTY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CART']: Exception("%ticker%: Data doesn't exist for startDate = 1679544000, endDate = 1695096000")

1 Failed download:
['SNVPR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['DRTT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PLNHF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RETA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SZL.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['INFI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['JUSH.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LBTY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['UBI']: Exception('%ticker%: No price data found, symbol may be delisted (1d 2023-09-11 00:00:00 -> 2024-03-09 00:00:00)')

1 Failed download:
['CCHW']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['JUSH.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CRDAC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CCHW']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['TRSSF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RETA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['TRSSF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CCHW']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CCHW']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PLNHF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LBTY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['JUPW']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CCHW']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ZANDZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BIOBI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SZL.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SZL.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['NH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CCHW']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LBTY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LBTY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BIOBI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FRG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FRG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FRG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FRG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FRG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ADER']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CCHW']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CCHW']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ZANDZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ZANDZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ZANDZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ZANDZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ZANDZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ZANDZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ZANDZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FORG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ZANDZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CCHW']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RETA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ADER']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RETA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SLGG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RETA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RETA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RETA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['YELL']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRIL']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRIL']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FORG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['YELL']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['YELL']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['YELL']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['YELL']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['YELL']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['YELL']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['YELL']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['YELL']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['YELL']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['NYT.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SGTX']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ACGN']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ACGN']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRTK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRTK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRTK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRTK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BRK.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ABC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['NEX']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['JUPW']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ABC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ZANDZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['NEX']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['NEX']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SURF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SURF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SURF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SURF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FORG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KDNY']: Exception('%ticker%: No timezone found, symbol may be delisted')

problem downloading nan: 'float' object has no attribute 'replace'

1 Failed download:
['YELL']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RETA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RETA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RETA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RETA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OXAC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SLGG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['YELL']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HYACU']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SLGG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VRAY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VRAY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SLGG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['NEX']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRNA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VRAY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BGRY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VRAY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VRAY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VRAY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VRAY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VRAY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SLGG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['NEX']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['NETD.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VRAY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PDCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FORG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SLGG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRIL']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LGF.B']: Exception('%ticker%: No price data found, symbol may be delisted (1d 2023-07-14 00:00:00 -> 2024-01-10 00:00:00)')

1 Failed download:
['ACGN']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SLGG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FORG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ABC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SLGG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SLGG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FISV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ISEE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FORG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SNFC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

problem downloading nan: 'float' object has no attribute 'replace'
problem downloading nan: 'float' object has no attribute 'replace'

1 Failed download:
['BFA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SLGG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['UBI']: Exception('%ticker%: No price data found, symbol may be delisted (1d 2023-06-30 00:00:00 -> 2023-12-27 00:00:00)')

1 Failed download:
['SZL.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LFAC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SLGG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BBLN']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['TRSSF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SZL.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['NOVN']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LBTY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BBLN']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SLGG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['TRSSF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BBLN']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BFA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['DICE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ABC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SDC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SZL.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FORG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BBLN']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LFAC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LBTY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SLGG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FORG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BBLN']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PDCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ABC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BIOBI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LSI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CVT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SLGG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RETA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ABC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RETA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SLGG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FORG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CHRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FORG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BTN']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FMDT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SLGG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HTGM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ROCC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LSI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LSI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CHRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['DRTT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CYXT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CYXT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CYXT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SLGG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BIOBI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['STSA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['STSA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SZL.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ISEE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['AMRS']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CHRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FMDT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PDCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['DICE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FISV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FORG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KDNY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SZL.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ENKR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PTRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PTRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SPPI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SIRE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['TCRR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SZL.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RENN']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PLNHF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LTRY']: Exception("%ticker%: Data doesn't exist for startDate = 1669266000, endDate = 1684814400")

1 Failed download:
['FORG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FORG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FORG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FORG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FORG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['TCRR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['TCRR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ZANDZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LTRY']: Exception("%ticker%: Data doesn't exist for startDate = 1669179600, endDate = 1684728000")

1 Failed download:
['ROCC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SZL.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SZL.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['DRTT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CREC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MNTV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MNTV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MNTV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MNTV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MNTV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MNTV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MNTV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ZANDZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ZANDZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ZANDZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ZANDZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ZANDZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ZANDZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ZANDZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ZANDZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ABC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PLNHF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PDCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OFC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ACGN']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FORG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ACGN']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['DRTT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['DRTT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RETA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RETA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RETA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RETA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RETA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RETA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PDCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ACGN']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RETA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['TCFC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['TCFC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['TCFC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ACGN']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ABC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['TCRR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HLBZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OBNK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LTRY']: Exception("%ticker%: Data doesn't exist for startDate = 1668056400, endDate = 1683604800")

1 Failed download:
['LTRY']: Exception("%ticker%: Data doesn't exist for startDate = 1668056400, endDate = 1683604800")

1 Failed download:
['ABC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['TCFC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['AQUA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BAMM']: Exception('%ticker%: No price data found, symbol may be delisted (1d 2023-05-08 00:00:00 -> 2023-11-04 00:00:00)')

1 Failed download:
['TCRR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['DICE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SCHN']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FISV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SCHN']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ZANDZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OBNK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OBNK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['DICE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['DICE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['DICE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SCHN']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SCHN']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['TCRR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OBNK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OBNK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OBNK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OBNK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OBNK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OBNK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ISEE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ISEE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FORG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FISV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PDCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OBNK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OBNK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['NYMX']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['NYMX']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KDNY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['TESS']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ISEE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ISEE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['NMTR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CEMI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['QGNC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['DICE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CEMI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ADEX.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KDNY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PDCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PDCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FORG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PKI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CEMI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ABC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PKI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CEMI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OBSV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BSTG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RXDX']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['AMRS']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRDS']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRDS']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['JNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CVT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KDNY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CEMI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SNFC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ISEE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KDNY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PDCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FORG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['N.A.']: Exception('%ticker%: No timezone found, symbol may be delisted')

problem downloading nan: 'float' object has no attribute 'replace'

1 Failed download:
['DICE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GMVD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['TBMCU']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['TBMCU']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PFHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['EMBK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['EMBK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['TRSSF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SDC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PKI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['TRSSF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KNWN']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['TRSSF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LBTY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['DICE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BFA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['DICE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ABST']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['TRSSF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PTRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PTRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PTRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FORG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ZANDZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['TRSSF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['TRSSF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['TRSSF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KNWN']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FISV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PGRW']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['USBL']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['TRSSF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['UHALU']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['UHALU']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['UHALU']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['DICE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['AZYO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SZL.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['TRSSF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['TRSSF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ABST']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['REVRQ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PDCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['TRSSF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FORG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PKI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['NYSE.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['DICE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRTK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['NYSE.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FORG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MNK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KNWN']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KNWN']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BBLN']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RXDX']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SUMO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SUMO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SUMO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SUMO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SUMO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SUMO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SUMO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PDCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['NYSE.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MCG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KNWN']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KNWN']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SPPI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SPPI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MAXR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FORG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:

['MNTV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ABC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MNK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MNK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OBNK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OBNK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BBLN']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RETA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MCG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ABST']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MNK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MNK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['JNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RSVB']: Exception('%ticker%: No price data found, symbol may be delisted (1d 2023-03-13 00:00:00 -> 2023-09-09 00:00:00)')

1 Failed download:
['VVNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VVNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RETA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MYOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['TRSSF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MSGE']: Exception("%ticker%: Data doesn't exist for startDate = 1662782400, endDate = 1678338000")

1 Failed download:
['AZYO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RXDX']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BIOBI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KLR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ZEST']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LBTY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RETA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RETA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RETA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RETA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RETA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RETA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ABST']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RXDX']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RETA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FORG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['NEX']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MAXR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MAXR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VRAY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LHDX']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LHDX']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LHDX']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LHDX']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RETA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RETA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RETA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RETA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['STNL']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['STNL']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KLR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SESN']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SESN']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SESN']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SESN']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SESN']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RETA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RETA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RETA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ISEE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BRK.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RETA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KLR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FRGFR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RXDX']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KLR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FISV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KDNY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ABC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MOGA.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PDCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KLR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KLR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KLR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KLR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CR']: Exception("%ticker%: Data doesn't exist for startDate = 1662004800, endDate = 1677560400")

1 Failed download:
['MAXR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MAXR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MAXR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MAXR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MAXR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OBSV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MAXR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MAXR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MAXR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MAXR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SIVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SIVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FRGFR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FRGFR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FRGFR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FRGFR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SPPI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SPPI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SESN']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SESN']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SESN']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SESN']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SESN']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PYX']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRTK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRTK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FORG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FORG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FORG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FORG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FORG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ISEE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MNTV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MNTV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MNTV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MNTV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MNTV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ZANDZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['DISTU']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FORG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LHDX']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ONEM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ONEM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ONEM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RXDX']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RXDX']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ZANDZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ZANDZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ZANDZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PDCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PDCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ZANDZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ZANDZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ZANDZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ZANDZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ZANDZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ABC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CVT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LGTO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['DBD']: Exception("%ticker%: Data doesn't exist for startDate = 1676350800, endDate = 1691899200")

1 Failed download:
['DBD']: Exception("%ticker%: Data doesn't exist for startDate = 1676350800, endDate = 1691899200")

1 Failed download:
['LGTO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['DBD']: Exception("%ticker%: Data doesn't exist for startDate = 1676264400, endDate = 1691812800")

1 Failed download:
['USBL']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KDNY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KDNY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KDNY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KDNY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ONCS']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CENQU']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MOGA.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ICCT']: Exception("%ticker%: Data doesn't exist for startDate = 1675832400, endDate = 1691380800")

1 Failed download:
['LGTO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['AQUA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MGTA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ABC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CR']: Exception("%ticker%: Data doesn't exist for startDate = 1660190400, endDate = 1675746000")

1 Failed download:
['INKA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MOGA.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CRTD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MCAE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['UNVR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['COUP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ISEE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SIVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LPI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PDCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FISV']: Exception('%ticker%: No timezone found, symbol may be delisted')

problem downloading nan: 'float' object has no attribute 'replace'
problem downloading nan: 'float' object has no attribute 'replace'

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KDNY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KDNY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KDNY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MOGA.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ICCT']: Exception("%ticker%: Data doesn't exist for startDate = 1675141200, endDate = 1690689600")

1 Failed download:
['KDNY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MSPR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['INKA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SPPI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SPPI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OBNK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['YELL']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BOXD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BOXD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BOXD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BOXD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BOXD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['AXAS']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PTRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MTCR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MTCR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['COUP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MOGA.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CTIC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CTIC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HSAQ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PTRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['AXAS']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FISV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['INKA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SIVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CRTD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['AXAS']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MYOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MYOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MYOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MYOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:

['FISV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RXDX']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RXDX']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FORG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ABC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PDCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PDCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HZNP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['DHHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RHE.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ICCT']: Exception("%ticker%: Data doesn't exist for startDate = 1673758800, endDate = 1689307200")

1 Failed download:
['ICCT']: Exception("%ticker%: Data doesn't exist for startDate = 1673758800, endDate = 1689307200")

1 Failed download:
['HZNP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['AXAS']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KMPH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KMPH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RHE.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['DHHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HPX']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HPX']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['INKA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRTY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HZNP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RCII']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['JNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['JNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['JNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['JNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RIDE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HZNP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HSKA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FISV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MOGA.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SMFR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SMFR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MYOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MYOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FISV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['UBA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CRTD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SPPI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['COUP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KDNY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ISEE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ISEE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ISEE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ISEE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PDCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LPI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SIVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HLBZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['N.A.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['N.A.']: Exception('%ticker%: No timezone found, symbol may be delisted')

problem downloading nan: 'float' object has no attribute 'replace'

1 Failed download:
['SMFR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RHE.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CTIC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CTIC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['COUP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SPNE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['NILE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['TRSSF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HLBZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['TUEM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SIVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RHE.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['UIHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['UIHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMGO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMGO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GLBL']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['TRSSF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MCG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RHE.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['USER']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ABC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HSKA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['UIHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CRTD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PKI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PKI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ABC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CR']: Exception("%ticker%: Data doesn't exist for startDate = 1660190400, endDate = 1675746000")

1 Failed download:
['INKA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MOGA.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CRTD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MCAE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['UNVR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['COUP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ISEE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SIVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LPI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PDCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FISV']: Exception('%ticker%: No timezone found, symbol may be delisted')

problem downloading nan: 'float' object has no attribute 'replace'
problem downloading nan: 'float' object has no attribute 'replace'

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KDNY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KDNY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KDNY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MOGA.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ICCT']: Exception("%ticker%: Data doesn't exist for startDate = 1675141200, endDate = 1690689600")

1 Failed download:
['KDNY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MSPR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['INKA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SPPI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SPPI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OBNK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['YELL']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BOXD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BOXD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BOXD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BOXD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BOXD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['AXAS']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PTRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MTCR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MTCR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['COUP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MOGA.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CTIC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CTIC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HSAQ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PTRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['AXAS']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FISV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['INKA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SIVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CRTD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['AXAS']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MYOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MYOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MYOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MYOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:

['FISV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RXDX']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RXDX']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FORG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ABC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PDCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PDCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HZNP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['DHHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RHE.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ICCT']: Exception("%ticker%: Data doesn't exist for startDate = 1673758800, endDate = 1689307200")

1 Failed download:
['ICCT']: Exception("%ticker%: Data doesn't exist for startDate = 1673758800, endDate = 1689307200")

1 Failed download:
['HZNP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['AXAS']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KMPH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KMPH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RHE.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['DHHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HPX']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HPX']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['INKA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRTY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HZNP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RCII']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['JNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['JNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['JNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['JNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RIDE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HZNP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HSKA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FISV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MOGA.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SMFR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SMFR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MYOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MYOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FISV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['UBA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CRTD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SPPI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['COUP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KDNY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ISEE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ISEE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ISEE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ISEE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PDCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LPI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SIVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HLBZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['N.A.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['N.A.']: Exception('%ticker%: No timezone found, symbol may be delisted')

problem downloading nan: 'float' object has no attribute 'replace'

1 Failed download:
['SMFR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RHE.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CTIC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CTIC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['COUP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SPNE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['NILE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['TRSSF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HLBZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['TUEM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SIVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RHE.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['UIHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['UIHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMGO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMGO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GLBL']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['TRSSF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MCG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RHE.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['USER']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ABC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HSKA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['UIHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CRTD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PKI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PKI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ABC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CR']: Exception("%ticker%: Data doesn't exist for startDate = 1660190400, endDate = 1675746000")

1 Failed download:
['INKA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MOGA.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CRTD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MCAE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['UNVR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['COUP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ISEE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SIVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LPI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PDCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FISV']: Exception('%ticker%: No timezone found, symbol may be delisted')

problem downloading nan: 'float' object has no attribute 'replace'
problem downloading nan: 'float' object has no attribute 'replace'

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KDNY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KDNY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KDNY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MOGA.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ICCT']: Exception("%ticker%: Data doesn't exist for startDate = 1675141200, endDate = 1690689600")

1 Failed download:
['KDNY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MSPR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['INKA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SPPI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SPPI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OBNK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['YELL']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BOXD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BOXD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BOXD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BOXD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BOXD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['AXAS']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PTRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MTCR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MTCR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['COUP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MOGA.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CTIC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CTIC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HSAQ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PTRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['AXAS']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FISV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['INKA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SIVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CRTD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['AXAS']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MYOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MYOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MYOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MYOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:

['FISV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RXDX']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RXDX']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FORG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ABC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PDCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PDCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HZNP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['DHHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RHE.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ICCT']: Exception("%ticker%: Data doesn't exist for startDate = 1673758800, endDate = 1689307200")

1 Failed download:
['ICCT']: Exception("%ticker%: Data doesn't exist for startDate = 1673758800, endDate = 1689307200")

1 Failed download:
['HZNP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['AXAS']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KMPH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KMPH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RHE.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['DHHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HPX']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HPX']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['INKA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRTY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HZNP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RCII']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['JNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['JNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['JNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['JNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RIDE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HZNP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HSKA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CCB']: Exception('%ticker%: No price data found, symbol may be delisted (1d 2022-07-09 00:00:00 -> 2023-01-05 00:00:00)')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FISV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MOGA.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SMFR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SMFR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MYOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MYOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FISV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['UBA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CRTD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SPPI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['COUP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KDNY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ISEE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ISEE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ISEE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ISEE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PDCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LPI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SIVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HLBZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['N.A.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['N.A.']: Exception('%ticker%: No timezone found, symbol may be delisted')

problem downloading nan: 'float' object has no attribute 'replace'

1 Failed download:
['SMFR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RHE.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CTIC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CTIC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['COUP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SPNE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['NILE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['TRSSF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HLBZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['TUEM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SIVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RHE.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['UIHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['UIHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMGO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMGO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GLBL']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['TRSSF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MCG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RHE.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['USER']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ABC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HSKA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['UIHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CRTD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PKI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PKI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ABC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CR']: Exception("%ticker%: Data doesn't exist for startDate = 1660190400, endDate = 1675746000")

1 Failed download:
['INKA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MOGA.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CRTD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MCAE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['UNVR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['COUP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ISEE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SIVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LPI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PDCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FISV']: Exception('%ticker%: No timezone found, symbol may be delisted')

problem downloading nan: 'float' object has no attribute 'replace'
problem downloading nan: 'float' object has no attribute 'replace'

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KDNY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KDNY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KDNY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MOGA.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ICCT']: Exception("%ticker%: Data doesn't exist for startDate = 1675141200, endDate = 1690689600")

1 Failed download:
['KDNY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MSPR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['INKA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SPPI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SPPI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OBNK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['YELL']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BOXD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BOXD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BOXD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BOXD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BOXD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['AXAS']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PTRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MTCR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MTCR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['COUP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MOGA.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CTIC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CTIC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HSAQ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PTRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['AXAS']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FISV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['INKA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SIVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CRTD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['AXAS']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MYOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MYOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MYOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MYOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:

['FISV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RXDX']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RXDX']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FORG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ABC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PDCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PDCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HZNP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['DHHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RHE.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ICCT']: Exception("%ticker%: Data doesn't exist for startDate = 1673758800, endDate = 1689307200")

1 Failed download:
['ICCT']: Exception("%ticker%: Data doesn't exist for startDate = 1673758800, endDate = 1689307200")

1 Failed download:
['HZNP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['AXAS']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KMPH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KMPH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RHE.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['DHHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HPX']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HPX']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['INKA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRTY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HZNP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RCII']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['JNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['JNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['JNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['JNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RIDE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HZNP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HSKA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FISV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MOGA.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SMFR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SMFR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MYOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MYOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FISV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['UBA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CRTD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SPPI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['COUP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KDNY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ISEE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ISEE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ISEE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ISEE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PDCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LPI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SIVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HLBZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['N.A.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['N.A.']: Exception('%ticker%: No timezone found, symbol may be delisted')

problem downloading nan: 'float' object has no attribute 'replace'

1 Failed download:
['SMFR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RHE.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CTIC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CTIC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['COUP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SPNE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['NILE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['TRSSF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HLBZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['TUEM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SIVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RHE.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['UIHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['UIHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMGO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMGO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GLBL']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['TRSSF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MCG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RHE.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['USER']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ABC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HSKA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['UIHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CRTD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PKI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PKI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ABC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CR']: Exception("%ticker%: Data doesn't exist for startDate = 1660190400, endDate = 1675746000")

1 Failed download:
['INKA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MOGA.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CRTD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MCAE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['UNVR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['COUP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ISEE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SIVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LPI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PDCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FISV']: Exception('%ticker%: No timezone found, symbol may be delisted')

problem downloading nan: 'float' object has no attribute 'replace'
problem downloading nan: 'float' object has no attribute 'replace'

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KDNY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KDNY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KDNY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MOGA.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ICCT']: Exception("%ticker%: Data doesn't exist for startDate = 1675141200, endDate = 1690689600")

1 Failed download:
['KDNY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MSPR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['INKA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SPPI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SPPI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OBNK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['YELL']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BOXD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BOXD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BOXD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BOXD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BOXD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['AXAS']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PTRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MTCR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MTCR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['COUP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MOGA.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CTIC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CTIC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HSAQ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PTRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['AXAS']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FISV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['INKA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SIVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CRTD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['AXAS']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MYOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MYOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MYOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MYOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:

['FISV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RXDX']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RXDX']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FORG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ABC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PDCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PDCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HZNP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['DHHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RHE.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ICCT']: Exception("%ticker%: Data doesn't exist for startDate = 1673758800, endDate = 1689307200")

1 Failed download:
['ICCT']: Exception("%ticker%: Data doesn't exist for startDate = 1673758800, endDate = 1689307200")

1 Failed download:
['HZNP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['AXAS']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KMPH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KMPH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RHE.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['DHHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HPX']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HPX']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['INKA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRTY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HZNP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RCII']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['JNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['JNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['JNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['JNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RIDE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HZNP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HSKA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FISV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MOGA.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SMFR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SMFR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MYOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MYOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FISV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['UBA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CRTD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SPPI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['COUP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KDNY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ISEE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ISEE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ISEE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ISEE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PDCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LPI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SIVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HLBZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['N.A.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['N.A.']: Exception('%ticker%: No timezone found, symbol may be delisted')

problem downloading nan: 'float' object has no attribute 'replace'

Failed to get ticker 'SMFR' reason: HTTPSConnectionPool(host='query1.finance.yahoo.com', port=443): Read timed out. (read timeout=10)

1 Failed download:
['SMFR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RHE.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CTIC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CTIC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['COUP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SPNE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['NILE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['TRSSF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HLBZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['TUEM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SIVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RHE.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['UIHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['UIHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMGO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMGO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GLBL']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['TRSSF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MCG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RHE.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['USER']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ABC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HSKA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['UIHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CRTD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PKI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PKI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ABC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CR']: Exception("%ticker%: Data doesn't exist for startDate = 1660190400, endDate = 1675746000")

1 Failed download:
['INKA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MOGA.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CRTD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MCAE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:

['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['UNVR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['COUP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ISEE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SIVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LPI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PDCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FISV']: Exception('%ticker%: No timezone found, symbol may be delisted')

problem downloading nan: 'float' object has no attribute 'replace'
problem downloading nan: 'float' object has no attribute 'replace'

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KDNY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KDNY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KDNY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MOGA.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ICCT']: Exception("%ticker%: Data doesn't exist for startDate = 1675141200, endDate = 1690689600")

1 Failed download:
['KDNY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MSPR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['INKA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SPPI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SPPI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OBNK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['YELL']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BOXD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BOXD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BOXD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BOXD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BOXD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['AXAS']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PTRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MTCR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MTCR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['COUP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MOGA.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CTIC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CTIC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HSAQ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PTRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['AXAS']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FISV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['INKA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SIVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CRTD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['AXAS']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MYOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MYOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MYOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MYOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:

['FISV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RXDX']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RXDX']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FORG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ABC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PDCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PDCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HZNP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['DHHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RHE.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ICCT']: Exception("%ticker%: Data doesn't exist for startDate = 1673758800, endDate = 1689307200")

1 Failed download:
['ICCT']: Exception("%ticker%: Data doesn't exist for startDate = 1673758800, endDate = 1689307200")

1 Failed download:
['HZNP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['AXAS']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KMPH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KMPH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RHE.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['DHHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HPX']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HPX']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['INKA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRTY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HZNP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RCII']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['JNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['JNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['JNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['JNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RIDE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HZNP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HSKA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FISV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MOGA.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SMFR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SMFR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MYOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MYOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FISV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['UBA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CRTD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SPPI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['COUP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KDNY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ISEE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ISEE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ISEE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ISEE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PDCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LPI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SIVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HLBZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['N.A.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['N.A.']: Exception('%ticker%: No timezone found, symbol may be delisted')

problem downloading nan: 'float' object has no attribute 'replace'

1 Failed download:
['SMFR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RHE.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CTIC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CTIC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['COUP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SPNE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['NILE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['TRSSF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HLBZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['TUEM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SIVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RHE.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['UIHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['UIHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMGO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMGO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GLBL']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['TRSSF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MCG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RHE.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['USER']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ABC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HSKA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['UIHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CRTD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PKI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PKI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ABC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CR']: Exception("%ticker%: Data doesn't exist for startDate = 1660190400, endDate = 1675746000")

1 Failed download:
['INKA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MOGA.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CRTD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MCAE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['UNVR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['COUP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ISEE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SIVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LPI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PDCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FISV']: Exception('%ticker%: No timezone found, symbol may be delisted')

problem downloading nan: 'float' object has no attribute 'replace'
problem downloading nan: 'float' object has no attribute 'replace'

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KDNY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KDNY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KDNY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MOGA.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ICCT']: Exception("%ticker%: Data doesn't exist for startDate = 1675141200, endDate = 1690689600")

1 Failed download:
['KDNY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MSPR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['INKA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SPPI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SPPI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OBNK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['YELL']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BOXD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BOXD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BOXD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BOXD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BOXD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['AXAS']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PTRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MTCR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MTCR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['COUP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MOGA.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CTIC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CTIC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HSAQ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PTRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['AXAS']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FISV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['INKA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SIVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CRTD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['AXAS']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MYOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MYOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MYOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MYOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:

['FISV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RXDX']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RXDX']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FORG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ABC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PDCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PDCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HZNP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['DHHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RHE.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ICCT']: Exception("%ticker%: Data doesn't exist for startDate = 1673758800, endDate = 1689307200")

1 Failed download:
['ICCT']: Exception("%ticker%: Data doesn't exist for startDate = 1673758800, endDate = 1689307200")

1 Failed download:
['HZNP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['AXAS']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KMPH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KMPH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RHE.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['DHHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HPX']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HPX']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['INKA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRTY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HZNP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RCII']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['JNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['JNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['JNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['JNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RIDE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HZNP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HSKA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FISV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MOGA.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SMFR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SMFR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MYOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MYOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FISV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['UBA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CRTD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SPPI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['COUP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KDNY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ISEE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ISEE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ISEE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ISEE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PDCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LPI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SIVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HLBZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['N.A.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['N.A.']: Exception('%ticker%: No timezone found, symbol may be delisted')

problem downloading nan: 'float' object has no attribute 'replace'

1 Failed download:
['SMFR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RHE.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CTIC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CTIC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['COUP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SPNE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['NILE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['TRSSF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HLBZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['TUEM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SIVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RHE.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['UIHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['UIHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMGO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMGO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GLBL']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['TRSSF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MCG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RHE.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['USER']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ABC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HSKA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['UIHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CRTD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PKI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PKI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ABC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CR']: Exception("%ticker%: Data doesn't exist for startDate = 1660190400, endDate = 1675746000")

1 Failed download:
['INKA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MOGA.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CRTD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MCAE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['UNVR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['COUP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ISEE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SIVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LPI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PDCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FISV']: Exception('%ticker%: No timezone found, symbol may be delisted')

problem downloading nan: 'float' object has no attribute 'replace'
problem downloading nan: 'float' object has no attribute 'replace'

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KDNY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KDNY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KDNY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MOGA.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ICCT']: Exception("%ticker%: Data doesn't exist for startDate = 1675141200, endDate = 1690689600")

1 Failed download:
['KDNY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MSPR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['INKA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SPPI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SPPI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OBNK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['YELL']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BOXD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BOXD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BOXD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BOXD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BOXD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['AXAS']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PTRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MTCR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MTCR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['COUP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MOGA.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CTIC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CTIC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HSAQ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PTRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['AXAS']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FISV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['INKA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SIVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CRTD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['AXAS']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MYOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MYOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MYOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MYOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:

['FISV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RXDX']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RXDX']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FORG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ABC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PDCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PDCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HZNP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['DHHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RHE.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ICCT']: Exception("%ticker%: Data doesn't exist for startDate = 1673758800, endDate = 1689307200")

1 Failed download:
['ICCT']: Exception("%ticker%: Data doesn't exist for startDate = 1673758800, endDate = 1689307200")

1 Failed download:
['HZNP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['AXAS']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KMPH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KMPH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RHE.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['DHHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HPX']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HPX']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['INKA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRTY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HZNP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RCII']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['JNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['JNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['JNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['JNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RIDE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HZNP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HSKA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FISV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MOGA.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SMFR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SMFR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MYOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MYOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FISV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['UBA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CRTD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SPPI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['COUP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KDNY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ISEE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ISEE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ISEE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ISEE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PDCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LPI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SIVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HLBZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['N.A.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['N.A.']: Exception('%ticker%: No timezone found, symbol may be delisted')

problem downloading nan: 'float' object has no attribute 'replace'

1 Failed download:
['SMFR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RHE.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CTIC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CTIC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['COUP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SPNE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['NILE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['TRSSF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HLBZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['TUEM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SIVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RHE.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['UIHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['UIHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMGO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMGO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GLBL']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['TRSSF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MCG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RHE.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['USER']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ABC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HSKA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['UIHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CRTD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PKI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PKI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ABC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CR']: Exception("%ticker%: Data doesn't exist for startDate = 1660190400, endDate = 1675746000")

1 Failed download:
['INKA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MOGA.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CRTD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MCAE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['UNVR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['COUP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ISEE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SIVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LPI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PDCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FISV']: Exception('%ticker%: No timezone found, symbol may be delisted')

problem downloading nan: 'float' object has no attribute 'replace'
problem downloading nan: 'float' object has no attribute 'replace'

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KDNY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KDNY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KDNY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MOGA.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ICCT']: Exception("%ticker%: Data doesn't exist for startDate = 1675141200, endDate = 1690689600")

1 Failed download:
['KDNY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MSPR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['INKA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SPPI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SPPI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OBNK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['YELL']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BOXD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BOXD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BOXD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BOXD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BOXD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['AXAS']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PTRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MTCR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MTCR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['COUP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MOGA.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CTIC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CTIC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HSAQ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PTRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['AXAS']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FISV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['INKA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SIVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CRTD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['AXAS']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MYOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MYOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MYOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MYOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:

['FISV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RXDX']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RXDX']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FORG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ABC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PDCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PDCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HZNP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['DHHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RHE.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ICCT']: Exception("%ticker%: Data doesn't exist for startDate = 1673758800, endDate = 1689307200")

1 Failed download:
['ICCT']: Exception("%ticker%: Data doesn't exist for startDate = 1673758800, endDate = 1689307200")

1 Failed download:
['HZNP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['AXAS']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KMPH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KMPH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RHE.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['DHHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HPX']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HPX']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['INKA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRTY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HZNP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RCII']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['JNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['JNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['JNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['JNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RIDE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HZNP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HSKA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FISV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MOGA.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SMFR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SMFR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MYOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MYOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FISV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['UBA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CRTD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SPPI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['COUP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KDNY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ISEE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ISEE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ISEE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ISEE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PDCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LPI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SIVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HLBZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['N.A.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['N.A.']: Exception('%ticker%: No timezone found, symbol may be delisted')

problem downloading nan: 'float' object has no attribute 'replace'

1 Failed download:
['SMFR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RHE.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CTIC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CTIC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['COUP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SPNE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['NILE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['TRSSF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HLBZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['TUEM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SIVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RHE.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['UIHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['UIHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMGO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMGO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GLBL']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['TRSSF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MCG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RHE.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['USER']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ABC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HSKA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['UIHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CRTD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PKI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PKI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ABC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CR']: Exception("%ticker%: Data doesn't exist for startDate = 1660190400, endDate = 1675746000")

1 Failed download:
['INKA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MOGA.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CRTD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MCAE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['UNVR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['COUP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ISEE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SIVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LPI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PDCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FISV']: Exception('%ticker%: No timezone found, symbol may be delisted')

problem downloading nan: 'float' object has no attribute 'replace'
problem downloading nan: 'float' object has no attribute 'replace'

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['XM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KDNY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KDNY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KDNY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MOGA.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ICCT']: Exception("%ticker%: Data doesn't exist for startDate = 1675141200, endDate = 1690689600")

1 Failed download:
['KDNY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MSPR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['INKA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SPPI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SPPI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OBNK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['YELL']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BOXD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BOXD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BOXD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BOXD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['BOXD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['AXAS']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PTRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MTCR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MTCR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['COUP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MOGA.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CTIC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CTIC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HSAQ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PTRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['AXAS']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FISV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['INKA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PEAR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SIVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CDAK']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CRTD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['AXAS']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MYOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MYOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MYOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MYOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:

['FISV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RXDX']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RXDX']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FORG']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ABC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PDCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PDCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HZNP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['DHHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RHE.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ICCT']: Exception("%ticker%: Data doesn't exist for startDate = 1673758800, endDate = 1689307200")

1 Failed download:
['ICCT']: Exception("%ticker%: Data doesn't exist for startDate = 1673758800, endDate = 1689307200")

1 Failed download:
['HZNP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['AXAS']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KMPH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KMPH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RHE.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['DHHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HPX']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HPX']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['INKA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRTY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HZNP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RCII']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['JNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['JNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['JNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['JNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RIDE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CNCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HZNP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HSKA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OPNT']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FISV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MOGA.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SMFR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SMFR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MYOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MYOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['FISV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['UBA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CRTD']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SPPI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['OSH']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['COUP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['KDNY']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ISEE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ISEE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ISEE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ISEE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PDCE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LPI']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['MLVF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SIVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HLBZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GRAMF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['N.A.']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['N.A.']: Exception('%ticker%: No timezone found, symbol may be delisted')

problem downloading nan: 'float' object has no attribute 'replace'

1 Failed download:
['SMFR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RHE.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CTIC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['CTIC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['VLDR']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['COUP']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SPNE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['NILE']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['TRSSF']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HLBZ']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['TUEM']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['SIVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMRA']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['HHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['RHE.A']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['UIHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['UIHC']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['LOV']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMGO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['IMGO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['PRVB']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['ALBO']: Exception('%ticker%: No timezone found, symbol may be delisted')

1 Failed download:
['GLBL']: Exception('%ticker%: No timezone found, symbol may be delisted')

#saving errors to csv to remove for (make sure file is closed)
error_tickers_list = pd.DataFrame({'ErrorTickers': error_tickers})
error_tickers_list.to_csv(r'C:\Users\lkasc\1 MIS 2040\Final Project\error_tickers.csv', index=False)

## Calculating Difference between Trade Date and Filing Date

In [ ]:
iaaii['FilingTime'] = (iaaii['FDate'] - iaaii['TDate']).dt.days

## Finalizing Data Types before Plotting

In [ ]:
iaaii.info()

In [ ]:
iaaii[["Bullish", "Neutral","Bearish","Bullish 8-Week Moving Average","Bull-Bear Spread"]] = iaaii[["Bullish", "Neutral","Bearish","Bullish 8-Week Moving Average","Bull-Bear Spread"]].apply(pd.to_numeric)
iaaii.info()

## Export to CSV
Ensures I have the database even when the notebook isn't running, and can use it for analysis

In [ ]:
iaaii.to_csv('iaaii.csv', index=False)

## Time to Run

In [ ]:
end_time = time.time()
total_runtime = end_time - start_time
total_runtime_minutes = total_runtime / 60
print(f"Total runtime seconds: {round(total_runtime,2)}")
print(f"Total runtime minutes: {round(total_runtime_minutes,2)}")